# Generated by Django 2.1.4 on 2020-02-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Execursion',
            fields=[
                ('id', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('detailPageName', models.CharField(blank=True, max_length=200)),
                ('portID', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('typology', models.CharField(blank=True, choices=[('29', '29'), ('84', '84')], max_length=200)),
                ('activityLevel', models.CharField(blank=True, max_length=150)),
                ('collectionType', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=200)),
                ('language', models.CharField(blank=True, choices=[('en', 'en'), ('fr', 'fr'), ('Gr', 'Gr')], max_length=20)),
                ('priceLevel', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('mealInfo', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=15)),
                ('shortDescription', models.CharField(blank=True, max_length=150)),
                ('longDecription', models.TextField(blank=True)),
                ('externalContent', models.BooleanField(default=False)),
                ('minimumAge', models.CharField(blank=True, max_length=15)),
                ('wheelChairAccessible', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Execursion',
                'verbose_name_plural': 'Execursions',
                'ordering': ('name',),
            },
        ),
    ]
