# Generated by Django 2.1.4 on 2020-02-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercusion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='execursion',
            old_name='external_content',
            new_name='externalContent',
        ),
        migrations.RenameField(
            model_name='execursion',
            old_name='wheel_chair_accessible',
            new_name='wheelChairAccessible',
        ),
        migrations.RemoveField(
            model_name='execursion',
            name='activity_level',
        ),
        migrations.RemoveField(
            model_name='execursion',
            name='data_page_name',
        ),
        migrations.RemoveField(
            model_name='execursion',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='execursion',
            name='meal_info',
        ),
        migrations.RemoveField(
            model_name='execursion',
            name='minimum_age',
        ),
        migrations.RemoveField(
            model_name='execursion',
            name='port_id',
        ),
        migrations.RemoveField(
            model_name='execursion',
            name='price_level',
        ),
        migrations.RemoveField(
            model_name='execursion',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='execursion',
            name='trip_type',
        ),
        migrations.AddField(
            model_name='execursion',
            name='activityLevel',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='execursion',
            name='dataPage_name',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='execursion',
            name='longDecription',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='execursion',
            name='mealInfo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='execursion',
            name='minimumAge',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='execursion',
            name='portID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='execursion',
            name='priceLevel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='execursion',
            name='shortDescription',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='execursion',
            name='tripType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='execursion',
            name='collectionType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='execursion',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='execursion',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='execursion',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'en'), ('fr', 'fr'), ('Gr', 'Gr')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='execursion',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='execursion',
            name='status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='execursion',
            name='typology',
            field=models.CharField(blank=True, choices=[(29, 29), (84, 84)], max_length=200, null=True),
        ),
    ]
