# Generated by Django 2.1.4 on 2020-02-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercusion', '0002_auto_20200214_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='execursion',
            old_name='dataPage_name',
            new_name='dataPageName',
        ),
        migrations.AlterField(
            model_name='execursion',
            name='longDecription',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
