# Generated by Django 2.1.4 on 2020-02-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercusion', '0003_auto_20200214_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='execursion',
            old_name='tripType',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='execursion',
            name='dataPageName',
        ),
        migrations.AddField(
            model_name='execursion',
            name='detailPageName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='execursion',
            name='id',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='execursion',
            name='longDecription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='execursion',
            name='typology',
            field=models.CharField(blank=True, choices=[('29', '29'), ('84', '84')], max_length=200, null=True),
        ),
    ]
