# Generated by Django 2.1.4 on 2020-02-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercusion', '0004_auto_20200214_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execursion',
            name='longDecription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='execursion',
            name='typology',
            field=models.CharField(blank=True, choices=[('29', '29'), ('84', '84')], max_length=200, null=True),
        ),
    ]
