# Generated by Django 2.1.4 on 2020-02-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercusion', '0004_auto_20200215_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='execursion',
            old_name='tripType',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='execursion',
            name='id',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
