# Generated by Django 2.1.4 on 2020-02-15 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exercusion', '0005_auto_20200215_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='execursion',
            old_name='dataPageName',
            new_name='detailPageName',
        ),
        migrations.AlterField(
            model_name='execursion',
            name='mealInfo',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='execursion',
            name='minimumAge',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='execursion',
            name='shortDescription',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
